import { IItem } from "../../../interfaces/definedmodels/ItemInterface"
const seedItems: IItem[] = [
  {
    "id": 10000001,
    "name": "Potion",
    "description": "Heals HP+500. Standard potion that heals your wounds. Although basic and does not heal much, the quality is consistent and the production processes are highly professional and standardized, making it very affordable and abundant in supply.",
    "type": "consumable",
    "effect": "heal_flat",
    "effectPower": 500,
    "basePrice": 100,
    "equipStatHp": 0,
    "equipStatEnergy": 0,
    "equipStatAtk": 0,
    "equipStatDef": 0,
    "equipStatSpd": 0,
    "equipStatHit": 0
  },
  {
    "id": 20000001,
    "name": "Shortsword",
    "description": "ATK+50. Basic mass-produced shortsword. Effective enough for common uses, having higher reach than knives while still relatively light for newbies and sturdy enough to last few rough combats makes it the common go-to weapon for new adventurers and army recruits alike.",
    "type": "weapon",
    "effect": "",
    "effectPower": 0,
    "basePrice": 1000,
    "equipStatHp": 0,
    "equipStatEnergy": 0,
    "equipStatAtk": 50,
    "equipStatDef": 0,
    "equipStatSpd": 0,
    "equipStatHit": 0
  },
  {
    "id": 30000001,
    "name": "Shirt",
    "description": "Max HP+50. Just a normal shirt, does not offer much protection.",
    "type": "armor",
    "effect": "",
    "effectPower": 0,
    "basePrice": 300,
    "equipStatHp": 0,
    "equipStatEnergy": 0,
    "equipStatAtk": 0,
    "equipStatDef": 10,
    "equipStatSpd": 0,
    "equipStatHit": 0
  },
  {
    "id": 40000001,
    "name": "Iron Ring",
    "description": "Max HP+10. Ring made out of iron, usually created using leftover iron scraps from other stuffs. It's really nothing special.",
    "type": "accessory",
    "effect": "",
    "effectPower": 0,
    "basePrice": 150,
    "equipStatHp": 10,
    "equipStatEnergy": 0,
    "equipStatAtk": 1,
    "equipStatDef": 1,
    "equipStatSpd": 0,
    "equipStatHit": 0
  },
  {
    "id": 40000002,
    "name": "Power Ring",
    "description": "ATK+10. This ring is enchanted with magic power that makes the user abit more powerful. That or the user feels that way because they believe this ring makes them more powerful.",
    "type": "accessory",
    "effect": "",
    "effectPower": 0,
    "basePrice": 1000,
    "equipStatHp": 0,
    "equipStatEnergy": 0,
    "equipStatAtk": 10,
    "equipStatDef": 0,
    "equipStatSpd": 0,
    "equipStatHit": 0
  },
  {
    "id": 50000001,
    "name": "Rock",
    "description": "Just a regular rock. Pretty worthless but getting hit by one sure hurts. Some craftsman might actually buy it as material to craft cheap items but mainly because they'd rather spend tiny amount of money to buy it rather than wasting time gathering it themselves.",
    "type": "etc",
    "effect": "",
    "effectPower": 0,
    "basePrice": 10,
    "equipStatHp": 0,
    "equipStatEnergy": 0,
    "equipStatAtk": 0,
    "equipStatDef": 0,
    "equipStatSpd": 0,
    "equipStatHit": 0
  }
]

export default seedItems;